frozePlayerLeaveMessage: '&c&lSTAFF &8&l> &7The frozen player &e<Player> &7has left the server!'
frozenInventoryTitle: '&c&lYOU ARE FROZEN'
serverName: '&b&lBestServer'
instructionMessage:
  line1: '&7Please join the Discord!'
  line2: '&b(Discord Link)'
  line3: '&cYou have been frozen!'
  line4: '&cBe prepared to be ScreenShared!'
placeHolderTitle: '&b&kiii&c&lYOU ARE FROZEN&b&kiii'
noPermission: '<ServerName> &8&l> &cYou do not have the Permission to do this!'
freezePlayerMessage: '<ServerName> &8&l> &7You have froze the player &e<Player>&7!'
unfreezePlayerMessage: '<ServerName> &8&l> &7You have unfroze the player &e<Player>&7!'
argsMessage: '<ServerName> &8&l> &7Incorrect Usage! &c/freeze (player)'
invalidPlayerMessage: '<ServerName> &8&l> &7Unavailable to find the player <Player>'
exemptMessage: '<ServerName> &8&l> &7The player <Player> is immune to being frozen!'
unfreezeMessage: '<ServerName> &8&l> &7You have been unfrozen!'